package net.foxopen.fox.thread;

import net.foxopen.fox.command.XDoResult;

/**
 * An alert message for the user's attention, typically generated by an fm:alert command.
 */
public class AlertMessage 
implements XDoResult {
  
  private final String mMessage;

  public AlertMessage(String pMessage) {
    mMessage = pMessage;
  }

  public String getMessage() {
    return mMessage;
  }
}
