package net.foxopen.fox.track;


/**
 * Flags for classifying Track messages for easier sorting and displaying to the user. FOX developers should add
 * additional flags as appropriate.
 */
public enum TrackFlag {
  /** Entries pertaining to running queries/APIs etc. */
  DATABASE_ACCESS(false),

  /** Entries pertaining to the execution of XDo Action code */
  ACTION_PROCESSING(false),

  /** Messages regarding badly-defined FOX components. */
  BAD_MARKUP(true),

  /** Messages containing details of a change in behaviour between engine versions. */
  REGRESSION_CHANGE(true),

  /** Warnings generated by the parse tree/HTML generation components. */
  PARSE_TREE_WARNING(true),

  /** General alerts which the developer should be aware of. ALERT level messages are given this flag by default. */
  ALERT(true),

  /** Messages generated by unit test style assertions - note: currently "for attention" until a better reporting mechanism is established for assertions */
  ASSERTION(true),

  /** Messages logged via the Logging.sysLogWarn() */
  FOX_SYS_LOG_WARNING(true);

  private final boolean mRequiresAttention;

  private TrackFlag(boolean pRequiresAttention) {
    mRequiresAttention = pRequiresAttention;
  }

  /**
   * Returns true if this track flag is considered important and requires attention from a developer.
   * @return
   */
  public boolean isRequiresAttention() {
    return mRequiresAttention;
  }
}
