package net.foxopen.fox.thread.alert;

import net.foxopen.fox.command.XDoResult;

/**
 * An alert message for the user's attention, typically generated by an fm:alert command.
 */
public interface AlertMessage
extends XDoResult { }
