package net.foxopen.fox.thread.alert;

/**
 * An alert message for the user's attention, typically generated by an fm:alert command.
 */
public class BasicAlertMessage
implements AlertMessage {

  private final String mMessage;

  public BasicAlertMessage(String pMessage) {
    mMessage = pMessage;
  }

  public String getMessage() {
    return mMessage;
  }
}
