package net.foxopen.fox.thread.alert;

/**
 * An basic textual message for the user's attention, typically generated by an fm:alert command. Apart from line breaks
 * denoted by the "\n" string (NOT the newline character), no formatting is allowed in the message.
 */
public class BasicAlertMessage
implements AlertMessage {

  private final String mMessage;

  /**
   * Creates a new alert message for displaying a simple string message.
   * @param pMessage Message to display.
   */
  public BasicAlertMessage(String pMessage) {
    mMessage = pMessage;
  }

  /**
   * @return The text of this alert message. "\n" string sequences should be converted to newlines in the required output format.
   */
  public String getMessage() {
    return mMessage;
  }
}
